#!/usr/bin/env bash
# Repeating best school 10 times

for Best School in 1 2 3 4 5 6 7 8 9 10 
do 
Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
Best School
done 
