#!/usr/bin/env bash
#were multiplying now
i=0
while [ "$i" -le 100 ]
do
	if [[ $((i%15)) == 0 ]]; then 
	       echo "FizzBuzz"
       elif [[ $((i%3)) == 0 ]]; then 
	       echo "Fizz"
       elif [[ $((i%5)) == 0 ]]; then 
	       echo "Buzz"
	fi
	((i++))
	echo "$i"
done	

