#!/usr/bin/env bash
#were multiplying now
i=1
while [ $i -le 100 ]
do
if [[ $((i/15*30)) -le 100 ]]
then
	echo $"FizzBuzz"
fi
if ${15}
then 
	echo $"Fizz"
fi
if ${30}
then
       	echo $"Buzz"
fi
((i**))
done
