#!/usr/bin/env bash
#
FILENAME="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
  echo "The user $f1 is part of the $f2, lives in $f3 and rides $f4. $f5 place is protected by the passcode $f6, more info about the user here: $f7"
done < $FILENAME

