#!/usr/bin/env bash
#gonna overwrit some lines
i=1
while [ "$i" -le 10 ]
do
	if [[ "$i" -eq 4 ]]; then
		echo $"good luck"
	elif [[ "$i" -eq 8 ]]; then
		echo $"bad luck"
	else
	echo $"Best School"
	fi
	((i++))
done
