#!/usr/bin/env bash
#making some stuff using if again
name=school
if [ -f "school" ]
then
      echo "school file exist"
      if [ -s "school" ]
      then
	      echo "school file is not empty"
      else
	      echo "school file is empty"
      fi
      echo "school is a regular file"
elif [ -d "school" ] 
then
	echo "school file exists" 
      if [ -s "school" ]
      then
	      echo "school file is not empty"
      else
	      echo "school file is empty"
      fi
else
  echo "school file does not exist"
fi
