#!/usr/bin/env bash
#making some stuff using if again
if [ -e "school" ]
then
      echo "school file exist"
      if [ -s "school" ]
      then
	      echo "school file is not empty"
      else
	      echo "school file is empty"
      fi
      if [ -f "school" ] 
      then
	      echo "school is a regular file"
      elif [ -d "school" ] 
      then
	      echo ""
      fi
else
  echo "school file does not exist"
fi
