#!/usr/bin/env bash
#
sudo touch /var/run/myscript.pid
bash bash -c 'echo "$$"' > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y u no love me?!"' SIGINT
while : 
do 
	echo "To infinity and beyond"
	sleep 2
	sudo rm -f '/var/run/myscript.pid; exit'
done

