#!/usr/bin/env bash
#
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while : 
do 
	echo "To infinity and beyond"
	sleep 2
done

