#!/usr/bin/env bash
#
sudo touch /var/run/myscript.pid
bash -c 'echo "$$"' > /var/run/myscript.pid
#DISPLAY I hate the kill command 2
#DISPLAY Y U no love me 3
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while : 
do 
	echo "To infinity and beyond"
	sleep 2
	sudo rm '/var/run/myscript.pid; exit'
done

